In [2]:
import pandas as pd
data = { "Age": [22, None, 29, None, 31],"City": ["Delhi", None, "Mumbai", None, "Chennai"],"Salary": [50000, 60000, None, None, 75000]}
df=pd.DataFrame(data)
print(df)

    Age     City   Salary
0  22.0    Delhi  50000.0
1   NaN     None  60000.0
2  29.0   Mumbai      NaN
3   NaN     None      NaN
4  31.0  Chennai  75000.0

In [4]:
print(df.fillna(0))

    Age     City   Salary
0  22.0    Delhi  50000.0
1   0.0        0  60000.0
2  29.0   Mumbai      0.0
3   0.0        0      0.0
4  31.0  Chennai  75000.0

In [5]:
print(df["Age"].fillna(df["Age"].mean()))

0    22.000000
1    27.333333
2    29.000000
3    27.333333
4    31.000000
Name: Age, dtype: float64

In [6]:
print(df["Age"].fillna(df["Age"].median()))

0    22.0
1    29.0
2    29.0
3    29.0
4    31.0
Name: Age, dtype: float64

In [7]:
print(df["City"].fillna(df["City"].mode()[0]))

0      Delhi
1    Chennai
2     Mumbai
3    Chennai
4    Chennai
Name: City, dtype: object

In [9]:
df.ffill()

    Age     City   Salary
0  22.0    Delhi  50000.0
1  22.0    Delhi  60000.0
2  29.0   Mumbai  60000.0
3  29.0   Mumbai  60000.0
4  31.0  Chennai  75000.0

In [10]:
df.bfill()

    Age     City   Salary
0  22.0    Delhi  50000.0
1  29.0   Mumbai  60000.0
2  29.0   Mumbai  75000.0
3  31.0  Chennai  75000.0
4  31.0  Chennai  75000.0

In [12]:
print(df.fillna(0, inplace=True))

None

In [13]:
import pandas as pd
import numpy as np
df = pd.DataFrame({"Marks": [50, np.nan, np.nan, 70, np.nan, np.nan, 90],"City": ["Delhi", "Mumbai", np.nan, np.nan, "Chennai", np.nan, np.nan]})
print("Original DataFrame:")
print(df)

Original DataFrame:
   Marks     City
0   50.0    Delhi
1    NaN   Mumbai
2    NaN      NaN
3   70.0      NaN
4    NaN  Chennai
5    NaN      NaN
6   90.0      NaN

In [15]:
print(df.ffill(limit=1))

   Marks     City
0   50.0    Delhi
1   50.0   Mumbai
2    NaN   Mumbai
3   70.0      NaN
4   70.0  Chennai
5    NaN  Chennai
6   90.0      NaN

In [16]:
print(df.bfill(limit=1))

   Marks     City
0   50.0    Delhi
1    NaN   Mumbai
2   70.0      NaN
3   70.0  Chennai
4    NaN  Chennai
5   90.0      NaN
6   90.0      NaN