In [3]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [4]:
data=pd.read_csv("data.csv")
data

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
df=pd.DataFrame(data)
d=df.fillna(0)
print(d)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      0.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   0.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [6]:
new_data=d.to_csv("Purchase.csv")

In [7]:
data=pd.read_csv("Purchase.csv")
data

   Unnamed: 0  Country   Age   Salary Purchased
0           0   France  44.0  72000.0        No
1           1    Spain  27.0  48000.0       Yes
2           2  Germany  30.0  54000.0        No
3           3    Spain  38.0  61000.0        No
4           4  Germany  40.0      0.0       Yes
5           5   France  35.0  58000.0       Yes
6           6    Spain   0.0  52000.0        No
7           7   France  48.0  79000.0       Yes
8           8  Germany  50.0  83000.0        No
9           9   France  37.0  67000.0       Yes

In [8]:
X=data[["Salary"]]
y=data["Purchased"]

In [9]:
x=np.array(X).reshape(-1, 1)
x

array([[72000.],
       [48000.],
       [54000.],
       [61000.],
       [    0.],
       [58000.],
       [52000.],
       [79000.],
       [83000.],
       [67000.]])

In [10]:
y=np.array(y).reshape(-1, 1)
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [11]:
model=KNeighborsClassifier(n_neighbors=3)

In [12]:
model.fit(x, y)

C:\Users\tamil\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [13]:
new_sal=[[63000]]
prediction=model.predict(new_sal)

In [14]:
print("Predicted result:",prediction[0])

Predicted result: Yes

In [15]:
data=pd.read_csv("netflix_titles.csv")
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [16]:
df=data[["release_year", "type"]]

In [17]:
df=df.dropna()

In [18]:
print(df.head())

   release_year     type
0          2020    Movie
1          2021  TV Show
2          2021  TV Show
3          2021  TV Show
4          2021  TV Show

In [19]:
X=data[["release_year"]]
y=data["type"]

In [20]:
model=KNeighborsClassifier(n_neighbors=3)

In [21]:
model.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [40]:
prediction=model.predict([[2020]])

C:\Users\tamil\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [41]:
print("Predicted Type:",prediction[0])

Predicted Type: Movie