In [1]:
import pandas as pd

In [4]:
data=pd.read_csv("hospital data analysis.csv")
data

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4
...,...,...,...,...,...,...,...,...,...,...
979,996,68,Male,Hypertension,Medication and Counseling,1000,70,No,Stable,4
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3
981,998,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,Recovered,4
982,999,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,Stable,2
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5

In [21]:
d={"Name":["Tamil","Gowtham","Nithish","Aakash","Hiran"],"Age":[21,18,15,20,5]}

In [22]:
c=pd.DataFrame(d)
c

      Name  Age
0    Tamil   21
1  Gowtham   18
2  Nithish   15
3   Aakash   20
4    Hiran    5

In [23]:
f=c.to_csv("Bro.csv")

In [24]:
data=pd.read_csv("Bro.csv")
data

   Unnamed: 0     Name  Age
0           0    Tamil   21
1           1  Gowtham   18
2           2  Nithish   15
3           3   Aakash   20
4           4    Hiran    5

In [25]:
print(data["Age"])

0    21
1    18
2    15
3    20
4     5
Name: Age, dtype: int64

In [26]:
print(data["Name"])

0      Tamil
1    Gowtham
2    Nithish
3     Aakash
4      Hiran
Name: Name, dtype: object

In [27]:
print(data["Name"],data["Age"])

0      Tamil
1    Gowtham
2    Nithish
3     Aakash
4      Hiran
Name: Name, dtype: object 0    21
1    18
2    15
3    20
4     5
Name: Age, dtype: int64

In [28]:
print(data.loc[0:1,["Name","Age"]])

      Name  Age
0    Tamil   21
1  Gowtham   18

In [29]:
print(data.loc[:,["Name","Age"]])

      Name  Age
0    Tamil   21
1  Gowtham   18
2  Nithish   15
3   Aakash   20
4    Hiran    5

In [30]:
data={"Name":["Ram","Sai","Ravi"],
      "Age":[20,21,19],
      "Marks":[85,90,88]}
data

{'Name': ['Ram', 'Sai', 'Ravi'], 'Age': [20, 21, 19], 'Marks': [85, 90, 88]}

In [33]:
df=pd.DataFrame(data)
df.to_csv("data.csv")
print(df)

   Name  Age  Marks
0   Ram   20     85
1   Sai   21     90
2  Ravi   19     88

In [36]:
df=pd.read_csv("data.csv")
print(df.head())

   Unnamed: 0  Name  Age  Marks
0           0   Ram   20     85
1           1   Sai   21     90
2           2  Ravi   19     88

In [37]:
print(df.tail())

   Unnamed: 0  Name  Age  Marks
0           0   Ram   20     85
1           1   Sai   21     90
2           2  Ravi   19     88

In [38]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  3 non-null      int64
 1   Name        3 non-null      object
 2   Age         3 non-null      int64
 3   Marks       3 non-null      int64
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes
None

In [39]:
print(df.describe())

       Unnamed: 0   Age      Marks
count         3.0   3.0   3.000000
mean          1.0  20.0  87.666667
std           1.0   1.0   2.516611
min           0.0  19.0  85.000000
25%           0.5  19.5  86.500000
50%           1.0  20.0  88.000000
75%           1.5  20.5  89.000000
max           2.0  21.0  90.000000

In [40]:
print(df[df["Marks"]>85])

   Unnamed: 0  Name  Age  Marks
1           1   Sai   21     90
2           2  Ravi   19     88

In [41]:
print(df[df["Age"]<20])

   Unnamed: 0  Name  Age  Marks
2           2  Ravi   19     88

In [43]:
data={"Department":["CSE","CSE","IT","IT"],
      "Salary":[50000,60000,70000,80000]}
data

{'Department': ['CSE', 'CSE', 'IT', 'IT'],
 'Salary': [50000, 60000, 70000, 80000]}

In [44]:
df=pd.DataFrame(data)

In [45]:
print(df.groupby("Department").mean())

             Salary
Department
CSE         55000.0
IT          75000.0

In [62]:
data={"Name":["Tamil","Gowtham","Aakash","Nithish","Hiran Pranav"]}
df=pd.DataFrame(data)
df["Department"]=[None,"AI-DS","IT","BIO","LKG"]
df["City"]=["Mumbai",None,"Chennai",None,"Bangalore"]
df = df.fillna("Unknown")
print(df)

           Name Department       City
0         Tamil    Unknown     Mumbai
1       Gowtham      AI-DS    Unknown
2        Aakash         IT    Chennai
3       Nithish        BIO    Unknown
4  Hiran Pranav        LKG  Bangalore

In [64]:
data={"Name":["Tamil","Gowtham","Aakash","Nithish","Hiran Pranav"]}
df=pd.DataFrame(data)
df["Department"]=[None,"AI-DS","IT","BIO","LKG"]
df["City"]=["Mumbai",None,"Chennai",None,"Bangalore"]
df["City"]=df["City"].fillna("Not Available")
df

           Name Department           City
0         Tamil       None         Mumbai
1       Gowtham      AI-DS  Not Available
2        Aakash         IT        Chennai
3       Nithish        BIO  Not Available
4  Hiran Pranav        LKG      Bangalore

In [66]:
data = {"Name": ["Tamil", "", "Gowtham"], "City": ["Chennai", "Salem", ""]}
df = pd.DataFrame(data)
df = df.replace("", "Unknown")
print(df)

      Name     City
0    Tamil  Chennai
1  Unknown    Salem
2  Gowtham  Unknown