In [1]:
a=10
a

10

In [2]:
a=10
b=20
a
b

20

In [3]:
a=[22,33,44,55]
a

[22, 33, 44, 55]

In [4]:
import numpy as np
arr=np.array(a)
arr

array([22, 33, 44, 55])

In [5]:
type(arr)

numpy.ndarray

In [6]:
mean=np.mean(arr)
mean

np.float64(38.5)

In [7]:
maxi=np.max(arr)
maxi

np.int64(55)

In [8]:
mini=np.min(arr)
mini

np.int64(22)

In [9]:
z=np.zeros([3,4])
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
o=np.ones([3,4])
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
r=np.random.rand(5,4)
r

array([[0.66436481, 0.90521276, 0.86127522, 0.74789758],
       [0.28637542, 0.14934157, 0.72893157, 0.63717083],
       [0.43405243, 0.60390271, 0.45858492, 0.20151371],
       [0.67826245, 0.31126303, 0.40472516, 0.20114061],
       [0.71589056, 0.28677139, 0.95289753, 0.36185602]])

In [16]:
a=np.array([11,22,33,44,55,66,77,88,99,12,23,34,45,67,89,90,9,8])
length=len(a)
length

18

In [17]:
shape=np.reshape(a,(3,6))
shape

array([[11, 22, 33, 44, 55, 66],
       [77, 88, 99, 12, 23, 34],
       [45, 67, 89, 90,  9,  8]])

In [21]:
b=np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
s=a[3:6]
s

array([44, 55, 66])

In [26]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(b/a)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]

In [27]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,5],[6,7],[8,9]])
c=np.dot(a,b)
c

array([[ 40,  46],
       [ 94, 109]])

In [28]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]

In [29]:
arr=np.array([5,4,3,2,1])
np.sort(arr)

array([1, 2, 3, 4, 5])

In [35]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10])
final=np.concatenate((a,b,c))
final

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr=np.array([1,2,2,3,4,5,6,3])
unique=np.unique(arr)
unique

array([1, 2, 3, 4, 5, 6])

In [45]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [42]:
arr=np.linspace(1,9,3)
arr

array([1., 5., 9.])

In [47]:
a=np.array([2,1,3,4,5])
print(np.argmax(a))

4

In [48]:
print(np.argmin(a))

1

In [52]:
print(np.where(a<3))

(array([0, 1]),)

In [53]:
print(np.cumsum(a))

[ 2  3  6 10 15]

In [59]:
r=np.random.randint(1,10,10)
print(r)

[4 7 7 7 8 4 8 4 3 2]

In [62]:
a=np.array([1,2,3,4])
b=np.array([8,7,6,5])
np.corrcoef(a,b)

array([[ 1., -1.],
       [-1.,  1.]])

In [64]:
a=np.array([1,2,3,4,5])
print(a[:3])

[1 2 3]

In [69]:
print(a[2:])
print(a[:3])
print(a[:-3])
print(a[-3:])

[3 4 5]
[1 2 3]
[1 2]
[3 4 5]

In [74]:
Arr=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,2]])
print(Arr[0:1,1:3])
print(Arr[:,1:2])
print(Arr[:,::2])

[[2 3]]
[[2]
 [4]
 [8]]
[[1 3]
 [3 5]
 [7 9]]

In [79]:
import pandas as pd
c=pd.read_csv("tourism_dataset.csv")
c

,Location,Country,Category,Visitors,Rating,Revenue,Accommodation_Available
0,kuBZRkVsAR,India,Nature,948853,1.32,84388.38,Yes
1,aHKUXhjzTo,USA,Historical,813627,2.01,802625.60,No
2,dlrdYtJFTA,Brazil,Nature,508673,1.42,338777.11,Yes
3,DxmlzdGkHK,Brazil,Historical,623329,1.09,295183.60,Yes
4,WJCCQlepnz,France,Cultural,124867,1.43,547893.24,No
...,...,...,...,...,...,...,...
5984,xAzwnVKAqz,USA,Urban,828137,1.97,132848.78,No
5985,IfKotyaJFC,France,Nature,276317,3.53,325183.96,Yes
5986,bPyubCWGgA,Egypt,Beach,809198,3.37,927336.50,No
5987,kkWIucpBnu,Egypt,Cultural,808303,2.52,115791.43,Yes
5988,gHXUrdticm,France,Cultural,40939,4.65,957026.85,Yes

In [80]:
d={"Name":["Tamil","Gowtham"],"Age":[21,18]}
c=pd.DataFrame(d)
c

      Name  Age
0    Tamil   21
1  Gowtham   18

In [81]:
f=c.to_csv("Brothers.csv")

In [82]:
d=pd.read_csv("Brothers.csv")
d

   Unnamed: 0     Name  Age
0           0    Tamil   21
1           1  Gowtham   18

In [84]:
Arr=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,2]])
print(Arr[1:2,:3])

[[3 4 5]]

In [85]:
arr=np.array([[10,11,12,13,14],[20,21,22,23,24],[30,31,32,33,34],[40,41,42,43,44]])

In [87]:
print(arr[::3,:1])

[[10]
 [40]]

In [89]:
print(arr[:,1:5:3])

[[11 14]
 [21 24]
 [31 34]
 [41 44]]

In [90]:
print(arr[1:4:2,0:5:2])

[[20 22 24]
 [40 42 44]]

In [92]:
print(arr[::-2,:])

[[40 41 42 43 44]
 [20 21 22 23 24]]

In [93]:
print(arr[:,4:0:-2])

[[14 12]
 [24 22]
 [34 32]
 [44 42]]

In [94]:
print(arr[3:0:-1,1:3])

[[41 42]
 [31 32]
 [21 22]]

In [95]:
print(arr[::2,::-1])

[[14 13 12 11 10]
 [34 33 32 31 30]]

In [96]:
print(arr[-1:-4:-2,::2])

[[40 42 44]
 [20 22 24]]